import React, { useMemo } from "react";

const users = [
  { id: Math.random(), name: "Robin" },
  { id: Math.random(), name: "Dennis" },
  { id: Math.random(), name: "Sharad" },
  { id: Math.random(), name: "Rohit" },
  { id: Math.random(), name: "Jeshan" },
  { id: Math.random(), name: "Samrat" },
  { id: Math.random(), name: "John" },
  { id: Math.random(), name: "Josh" },
  { id: Math.random(), name: "hello" },
  { id: Math.random(), name: "hello1" },
  { id: Math.random(), name: "Hello2" },
  { id: Math.random(), name: "Hello3" },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` },
  { id: Math.random(), name: `Hello${Math.random()}` }
];

const App = () => {
  const [text, setText] = React.useState("");
  const [search, setSearch] = React.useState("");

  const handleText = (event) => {
    setText(event.target.value);
  };

  const handleSearch = () => {
    setSearch(text);
  };

  const filteredUsers = useMemo(
    () =>
      users.filter((eachUser) => {
        console.log("I am running man.");
        return eachUser.name.toLowerCase().includes(search.toLowerCase());
      }),
    [search]
  );

  return (
    <div>
      <input type="text" value={text} onChange={handleText} />
      <button type="button" onClick={handleSearch}>
        Search
      </button>

      <List list={filteredUsers} />
    </div>
  );
};

const List = ({ list }) => {
  return (
    <ul>
      {list.map((item) => (
        <ListItem key={item.id} item={item} />
      ))}
    </ul>
  );
};

const ListItem = ({ item }) => {
  return <li>{item.name}</li>;
};

export default App;
